### ISSUE TITLE
03/03 - Code review #Team94 

### ISSUE THREAD

**Issue by idgm5** [ferbaco86/Old-Apple-website-clone#2]
We know @ferbaco86 is already in the JS section with Thiago, so just try to find a typo or something so we don't leave this issue empty.

**Comment by idgm5** [comment]
Move the custom sizes to the parent property instead of the child:

```
position: relative;
    display: flex;
    justify-content: space-evenly;
    align-items: center;
    top: 202px;
    cursor: pointer;
    height: 15rem;
```

```
.promo-img {
    width: 100%;
    height: 100%;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
```

You only have to figure out if 15rem is enough as height in bigger resolutions. 

Here more examples of the background-size property:
https://www.w3schools.com/cssref/css3_pr_background-size.asp

**Comment by idgm5** [comment]
From K:
use this to validate your css https://jigsaw.w3.org/css-validator/ 
https://speckyboy.com/good-bad-css-practices/ From this 
^^^^ 
No errors but 2 warnings though 
Flex is in further section I think but upto this it is ok now. 

oh sorry Flexbox is in this section only I haven't done the reading though as no coding partner for me right now and the hacker issue. 

we could read this and do the assignment though for understanding flexbox 

https://www.theodinproject.com/courses/html5-and-css3/lessons/flexbox 

read this for good selectors https://speckyboy.com/good-bad-css-practices/

**Comment by ferbaco86** [comment]
Thanks for the comments!
The issue has been fix now
